### ISSUE TITLE
请教一下为什么 VideoFrame 不能直接转成 Mat ？

### ISSUE THREAD

**Issue by imndx** [GY-code/Vision#1]
如下面所示：
为什么不能直接将```VideoFrame```转成```Mat```进行处理，而是先转成```Bitmap```再转成```Mat``？

https://github.com/GY-code/Vision/blob/44e1f6d326f5f90f5cb2530b3e2ac8491c0a17fb/app/src/main/java/t20220049/sw_vision/webRTC_utils/ProxyVideoSink.java#L292-L301

**Comment by GY-code** [comment]
您好@imndx，这里的思路如您所说，先将`VideoFrame`转到`bitmap`再转到`Mat`，进行`OpenCV`相关的处理。开发过程中应该是没有找到直接从`VideoFrame`转到`Mat`的方法，如果您这边有好的建议欢迎提出。

> 如下面所示： 为什么不能直接将`VideoFrame`转成`Mat`进行处理，而是先转成`Bitmap`再转成```Mat``？
> 
> https://github.com/GY-code/Vision/blob/44e1f6d326f5f90f5cb2530b3e2ac8491c0a17fb/app/src/main/java/t20220049/sw_vision/webRTC_utils/ProxyVideoSink.java#L292-L301

**Comment by imndx** [comment]
好的，谢谢你的回复。

我尝试过 ```VideoFrame```直接转成```Mat```，然后进行处理，但发现有些问题，比如画一个矩形的话，会出来好几个，感觉是转的问题。

**Comment by GY-code** [comment]
好的，不客气
